# Generated by Django 3.0.6 on 2020-07-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nicName',
            new_name='nickName',
        ),
    ]
