# Generated by Django 3.0.6 on 2020-07-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200707_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='crreated_on',
            new_name='created_on',
        ),
    ]
